### ISSUE TITLE
没有找到queryString，在post中

### ISSUE THREAD

**Issue by XIAObackZI** [Gloridust/RuijieWIFI-AutoLogin#1]
![image](https://github.com/Gloridust/RuijieWIFI-AutoLogin/assets/131877168/f714d218-4a1b-4ea5-b9b8-1f93baa34193)

**Comment by XIAObackZI** [comment]
求带q 2977227390

**Comment by XIAObackZI** [comment]
一直请求登录中，并未成功

**Comment by Gloridust** [comment]
> 一直请求登录中，并未成功

1. 有些用户确实一直循环显示段断连，但是实际上可以使用。请检查是否可以连接到互联网；
2. 有些字段找不到也是玄学，建议退出登录后清除缓存多尝试

有其他问题欢迎留issues :-)

**Comment by XIAObackZI** [comment]
大佬，并未成功登录，我完全按照代码中的提示来操作的。

**Comment by Gloridust** [comment]
已添加q

**Comment by GuDong2003** [comment]
我实际操作过程中 也没有找个这个字段 不过我参考作者照片中类似于 wlannacname 或者 wlanserip 的字段复制之后发现可行 你可以再找找 试试
